# Generated by Django 5.2.4 on 2025-08-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='long_term_goals',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='long_term_goals',
            name='start_date',
            field=models.DateField(),
        ),
    ]
